name: Bot Apuestas Diario

on:
  push:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

jobs:
  ejecutar-modelo:
    runs-on: ubuntu-latest
    
    steps:
    - name: Bajar el código
      uses: actions/checkout@v3
      
    - name: Preparar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Instalar Herramientas
      run: |
        python -m pip install --upgrade pip
        pip install requests pandas scipy numpy
        
    - name: Ejecutar el Cerebro
      run: python modelo.py
      
    - name: Guardar el CSV en GitHub
      run: |
        git config --local user.email "bot@apuestas.com"
        git config --local user.name "Bot Apuestas"
        git add analisis_over25.csv
        git commit -m "Actualizando datos" || echo "No hay cambios para guardar"
        git push
